export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const START_API_REQUEST = 'START_API_REQUEST';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const LOAD_ADMINS_SUCCESS = 'LOAD_ADMINS_SUCCESS';
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';
export const REMOVE_ADMIN_SUCCESS = 'REMOVE_ADMIN_SUCCESS';
